import {
  db,
  companiesTable,
  investorsTable,
  dealsTable,
  activityTable,
} from "@workspace/db";

async function main() {
  console.log("Clearing existing seed data...");
  await db.delete(activityTable);
  await db.delete(dealsTable);
  await db.delete(investorsTable);
  await db.delete(companiesTable);

  const founders = [
    { name: "Maya Calderon", title: "Co-Founder & CEO" },
    { name: "Jonas Friedrich", title: "Founder & CEO" },
    { name: "Priya Raman", title: "CEO & President" },
    { name: "Ethan Park", title: "Founder & CTO" },
    { name: "Aisha Kone", title: "Co-Founder & COO" },
    { name: "Marco Vitale", title: "Founder & CEO" },
    { name: "Hannah Linder", title: "President" },
    { name: "Diego Salas", title: "Founder & CEO" },
    { name: "Yumi Nakamura", title: "CEO" },
    { name: "Owen Whittaker", title: "Founder" },
    { name: "Noor Hassan", title: "Co-Founder & CFO" },
    { name: "Tomas Halvorsen", title: "Co-Founder" },
  ];

  const heroImages = [
    "https://images.unsplash.com/photo-1497366216548-37526070297c?w=1600",
    "https://images.unsplash.com/photo-1518770660439-4636190af475?w=1600",
    "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=1600",
    "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=1600",
    "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=1600",
    "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=1600",
    "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=1600",
    "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=1600",
    "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=1600",
    "https://images.unsplash.com/photo-1556761175-b413da4baf72?w=1600",
    "https://images.unsplash.com/photo-1542744095-291d1f67b221?w=1600",
    "https://images.unsplash.com/photo-1483478550801-ceba5fe50e8e?w=1600",
  ];

  const cities = [
    "San Francisco, CA",
    "New York, NY",
    "Austin, TX",
    "London, UK",
    "Singapore",
    "Berlin, Germany",
    "Toronto, ON",
    "Boston, MA",
    "Amsterdam, NL",
    "Stockholm, Sweden",
    "Miami, FL",
    "Seattle, WA",
  ];

  const company = (
    id: string,
    name: string,
    tagline: string,
    industry: string,
    stage: string,
    founderIdx: number,
    revenue: number,
    raise: number,
    valuation: number,
    margin: number,
    growth: number,
    minInv: number,
    foundedYear: number,
    cityIdx: number,
    heroIdx: number,
    featured: boolean,
    overview: string,
    highlights: string[],
    useOfFunds: { label: string; percent: number }[],
    financials: { year: number; revenue: number; ebitda: number }[],
  ) => {
    const founder = founders[founderIdx % founders.length];
    return {
      id,
      name,
      tagline,
      industry,
      stage,
      headquarters: cities[cityIdx % cities.length],
      foundedYear,
      logoUrl: `https://api.dicebear.com/9.x/shapes/svg?seed=${encodeURIComponent(name)}&backgroundColor=0f3a6e,0a4d8f,11567a,1d6fb8`,
      heroImageUrl: heroImages[heroIdx % heroImages.length],
      annualRevenue: String(revenue),
      ebitdaMargin: String(margin),
      growthRate: String(growth),
      raiseAmount: String(raise),
      valuation: String(valuation),
      minimumInvestment: String(minInv),
      committedAmount: String(Math.round(raise * (0.25 + Math.random() * 0.55))),
      investorCount: 8 + Math.floor(Math.random() * 90),
      deadline: new Date(Date.now() + (30 + Math.floor(Math.random() * 90)) * 86400000)
        .toISOString()
        .slice(0, 10),
      featured,
      overview,
      useOfFunds,
      highlights,
      financials,
      team: [
        {
          name: founder.name,
          title: founder.title,
          bio: `${founder.name} has led ${name} since founding, growing the business to its current scale with a focus on disciplined unit economics.`,
          avatarUrl: `https://api.dicebear.com/9.x/personas/svg?seed=${encodeURIComponent(founder.name)}`,
        },
        {
          name: founders[(founderIdx + 1) % founders.length].name,
          title: "Chief Operating Officer",
          bio: `Operates the ${industry} business with two decades of execution experience.`,
          avatarUrl: `https://api.dicebear.com/9.x/personas/svg?seed=${encodeURIComponent(founders[(founderIdx + 1) % founders.length].name)}`,
        },
        {
          name: founders[(founderIdx + 2) % founders.length].name,
          title: "Chief Financial Officer",
          bio: `Leads finance, treasury, and capital strategy for the company.`,
          avatarUrl: `https://api.dicebear.com/9.x/personas/svg?seed=${encodeURIComponent(founders[(founderIdx + 2) % founders.length].name)}`,
        },
      ],
      documents: [
        { name: "Investor Pitch Deck", kind: "pitch_deck" as const },
        { name: "Audited Financial Statements", kind: "financials" as const },
        { name: "Term Sheet", kind: "term_sheet" as const },
        { name: "Due Diligence Pack", kind: "due_diligence" as const },
      ],
    };
  };

  const companies = [
    company(
      "co_orbit",
      "Orbit Logistics",
      "AI-powered last mile orchestration for grocery and pharmacy",
      "industrial",
      "series_b",
      0,
      28_400_000,
      18_000_000,
      135_000_000,
      19,
      71,
      25_000,
      2018,
      0,
      0,
      true,
      "Orbit operates the routing and dispatch backbone for 1,400+ regional grocery and pharmacy chains across North America. Our network optimizes delivery density across overlapping fleets, reducing cost per stop by 41% versus in-house alternatives. We are profitable, growing, and now expanding into pharmacy compliance workflows.",
      [
        "$28.4M ARR with 71% YoY growth and 19% EBITDA margin",
        "Multi-year contracts with 5 of the top 25 US grocery chains",
        "Net revenue retention of 138% over the last 12 months",
        "Patent-pending dispatch engine handling 2.4M deliveries / week",
      ],
      [
        { label: "Engineering & ML", percent: 35 },
        { label: "Pharmacy expansion", percent: 25 },
        { label: "Sales & enterprise GTM", percent: 22 },
        { label: "Working capital", percent: 18 },
      ],
      [
        { year: 2022, revenue: 9_100_000, ebitda: 600_000 },
        { year: 2023, revenue: 16_600_000, ebitda: 2_200_000 },
        { year: 2024, revenue: 28_400_000, ebitda: 5_400_000 },
      ],
    ),
    company(
      "co_clearwave",
      "Clearwave Health",
      "Specialty cardiology clinics for underserved metros",
      "healthcare",
      "growth",
      2,
      62_000_000,
      45_000_000,
      320_000_000,
      24,
      38,
      50_000,
      2014,
      1,
      1,
      true,
      "Clearwave operates 38 specialty cardiology clinics across the US Sun Belt, focused on underserved suburban and tertiary markets. Our model pairs board-certified cardiologists with on-site imaging and same-day procedural capability, generating dramatically better patient outcomes at 60% of the cost of hospital systems.",
      [
        "$62M revenue, 24% EBITDA margin, 38% YoY growth",
        "98.4% patient satisfaction across 38 clinics",
        "Contracted with all major US payors",
        "Strong de-novo playbook: clinics break even in <14 months",
      ],
      [
        { label: "De-novo clinic openings", percent: 55 },
        { label: "Imaging equipment", percent: 22 },
        { label: "Clinical leadership hiring", percent: 13 },
        { label: "Operating capital", percent: 10 },
      ],
      [
        { year: 2022, revenue: 32_000_000, ebitda: 5_200_000 },
        { year: 2023, revenue: 45_000_000, ebitda: 9_400_000 },
        { year: 2024, revenue: 62_000_000, ebitda: 14_900_000 },
      ],
    ),
    company(
      "co_meridian",
      "Meridian Capital Markets",
      "Embedded fixed income for wealth platforms",
      "fintech",
      "series_c",
      1,
      41_000_000,
      30_000_000,
      410_000_000,
      28,
      54,
      100_000,
      2016,
      2,
      2,
      true,
      "Meridian provides the API and operating layer for fractional fixed income inside wealth platforms, RIAs and private banks. We currently power $9.2B in client assets across 47 enterprise customers and are profitable with 28% EBITDA margin.",
      [
        "$41M ARR, 54% growth, 28% EBITDA margin",
        "$9.2B in client assets routed through the platform",
        "47 enterprise customers including 3 of the top 10 RIAs",
        "Regulatory infrastructure across 11 jurisdictions",
      ],
      [
        { label: "Product & engineering", percent: 40 },
        { label: "International expansion", percent: 28 },
        { label: "Compliance & regulatory", percent: 17 },
        { label: "GTM", percent: 15 },
      ],
      [
        { year: 2022, revenue: 18_500_000, ebitda: 3_100_000 },
        { year: 2023, revenue: 26_700_000, ebitda: 6_500_000 },
        { year: 2024, revenue: 41_000_000, ebitda: 11_500_000 },
      ],
    ),
    company(
      "co_northwind",
      "Northwind Renewables",
      "Distributed solar + storage for mid-market industrial sites",
      "energy",
      "growth",
      6,
      88_000_000,
      75_000_000,
      540_000_000,
      21,
      44,
      100_000,
      2012,
      3,
      3,
      true,
      "Northwind develops, finances, and operates rooftop and behind-the-meter solar plus storage for industrial campuses across the UK and EU. Our platform owns 412 MW of operating assets and has a 1.1 GW development pipeline.",
      [
        "412 MW operating, 1.1 GW pipeline",
        "$88M revenue, 21% EBITDA margin",
        "Long-duration PPAs averaging 14 years",
        "Investment-grade offtakers across portfolio",
      ],
      [
        { label: "Project capital", percent: 60 },
        { label: "Development team", percent: 18 },
        { label: "Storage R&D", percent: 12 },
        { label: "G&A", percent: 10 },
      ],
      [
        { year: 2022, revenue: 41_000_000, ebitda: 6_800_000 },
        { year: 2023, revenue: 62_000_000, ebitda: 11_900_000 },
        { year: 2024, revenue: 88_000_000, ebitda: 18_500_000 },
      ],
    ),
    company(
      "co_arboretum",
      "Arboretum Mills",
      "Heritage flour and baked goods for premium grocery",
      "consumer",
      "series_b",
      4,
      52_000_000,
      22_000_000,
      210_000_000,
      18,
      33,
      25_000,
      2009,
      4,
      4,
      false,
      "Arboretum mills heritage and ancient grains and supplies premium grocery, hospitality, and DTC subscribers across 11,000+ retail doors. We own our supply chain from farm to mill to packaging, generating durable margin and a recognized national brand.",
      [
        "$52M revenue, 33% YoY growth, 18% EBITDA",
        "11,000+ retail doors including Whole Foods and Wegmans",
        "Owned milling and supply chain",
        "DTC subscriber base of 142,000",
      ],
      [
        { label: "Mill capacity expansion", percent: 45 },
        { label: "Brand & marketing", percent: 25 },
        { label: "DTC infrastructure", percent: 18 },
        { label: "Working capital", percent: 12 },
      ],
      [
        { year: 2022, revenue: 28_000_000, ebitda: 3_900_000 },
        { year: 2023, revenue: 39_000_000, ebitda: 6_500_000 },
        { year: 2024, revenue: 52_000_000, ebitda: 9_400_000 },
      ],
    ),
    company(
      "co_lumen",
      "Lumen Vertical SaaS",
      "Operating system for independent veterinary clinics",
      "saas",
      "series_a",
      3,
      11_400_000,
      14_000_000,
      90_000_000,
      14,
      96,
      10_000,
      2020,
      5,
      5,
      true,
      "Lumen replaces 6 disconnected systems for independent veterinary clinics with one operating system handling EMR, scheduling, payments, inventory, and analytics. We serve 1,800+ clinics with NRR of 142%.",
      [
        "$11.4M ARR, 96% YoY growth, 14% EBITDA",
        "1,800+ active clinics, 142% NRR",
        "98% gross retention",
        "Embedded payments handling $620M GTV",
      ],
      [
        { label: "Engineering", percent: 38 },
        { label: "Sales & customer success", percent: 32 },
        { label: "Marketing", percent: 18 },
        { label: "G&A", percent: 12 },
      ],
      [
        { year: 2022, revenue: 2_900_000, ebitda: -1_100_000 },
        { year: 2023, revenue: 5_800_000, ebitda: 200_000 },
        { year: 2024, revenue: 11_400_000, ebitda: 1_600_000 },
      ],
    ),
    company(
      "co_atrium",
      "Atrium Modular",
      "Factory-built multifamily housing for urban infill",
      "real_estate",
      "growth",
      5,
      71_000_000,
      55_000_000,
      380_000_000,
      16,
      28,
      50_000,
      2015,
      6,
      6,
      false,
      "Atrium operates two modular factories in Ontario producing complete multifamily housing units assembled on urban infill sites in 60-day windows. We have delivered 4,300+ units to date and have $312M in contracted backlog.",
      [
        "$71M revenue, 16% EBITDA margin, 28% growth",
        "4,300+ units delivered to date",
        "$312M contracted backlog",
        "Two operating factories with 1.2M sq ft capacity",
      ],
      [
        { label: "Third factory build", percent: 48 },
        { label: "Production automation", percent: 22 },
        { label: "Pipeline acquisition", percent: 18 },
        { label: "Working capital", percent: 12 },
      ],
      [
        { year: 2022, revenue: 41_000_000, ebitda: 5_600_000 },
        { year: 2023, revenue: 56_000_000, ebitda: 8_100_000 },
        { year: 2024, revenue: 71_000_000, ebitda: 11_400_000 },
      ],
    ),
    company(
      "co_relay",
      "Relay Intelligence",
      "Applied AI for insurance claims operations",
      "ai",
      "series_b",
      7,
      19_800_000,
      26_000_000,
      210_000_000,
      11,
      114,
      25_000,
      2021,
      7,
      7,
      true,
      "Relay automates first-notice-of-loss triage, document extraction, and adjuster decisioning for mid-market property and casualty carriers. Our system handles 1.4M claim events monthly across 38 carriers.",
      [
        "$19.8M ARR, 114% growth",
        "38 enterprise carriers, 1.4M monthly claim events",
        "Average customer reduces cycle time by 47%",
        "Patent-pending document extraction stack",
      ],
      [
        { label: "Model & infra", percent: 40 },
        { label: "Enterprise GTM", percent: 30 },
        { label: "International expansion", percent: 18 },
        { label: "Compliance", percent: 12 },
      ],
      [
        { year: 2022, revenue: 2_100_000, ebitda: -2_900_000 },
        { year: 2023, revenue: 9_300_000, ebitda: -800_000 },
        { year: 2024, revenue: 19_800_000, ebitda: 2_200_000 },
      ],
    ),
    company(
      "co_harborline",
      "Harborline Maritime",
      "Short-sea container shipping across Northern Europe",
      "industrial",
      "growth",
      9,
      124_000_000,
      90_000_000,
      720_000_000,
      22,
      19,
      100_000,
      2008,
      9,
      9,
      false,
      "Harborline operates a fleet of 18 vessels providing short-sea container shipping between 24 ports across Northern Europe. We are a profitable consolidator in a fragmented sub-segment of European shipping.",
      [
        "$124M revenue, 22% EBITDA margin",
        "Fleet of 18 vessels, 24 port network",
        "Long-term contracts with 4 of top 10 European 3PLs",
        "Replacement cost of fleet exceeds enterprise value",
      ],
      [
        { label: "Fleet renewal (LNG dual-fuel)", percent: 65 },
        { label: "Port automation", percent: 18 },
        { label: "Software platform", percent: 10 },
        { label: "Working capital", percent: 7 },
      ],
      [
        { year: 2022, revenue: 92_000_000, ebitda: 16_500_000 },
        { year: 2023, revenue: 108_000_000, ebitda: 21_000_000 },
        { year: 2024, revenue: 124_000_000, ebitda: 27_300_000 },
      ],
    ),
    company(
      "co_silvermark",
      "Silvermark Skincare",
      "Clinical-grade dermatology products through licensed providers",
      "consumer",
      "series_b",
      8,
      34_000_000,
      20_000_000,
      180_000_000,
      26,
      59,
      10_000,
      2017,
      10,
      10,
      true,
      "Silvermark develops clinical-grade skincare distributed exclusively through 4,200+ licensed dermatology and cosmetic practices. Our practitioner channel produces high gross margins and unusually durable repeat purchase behavior.",
      [
        "$34M revenue, 26% EBITDA, 59% growth",
        "4,200+ practitioner accounts, 91% reorder rate",
        "Proprietary actives with 7 issued patents",
        "Average practitioner spends $7,800/yr",
      ],
      [
        { label: "Lab & R&D", percent: 32 },
        { label: "Practitioner sales force", percent: 38 },
        { label: "International expansion", percent: 18 },
        { label: "Operations", percent: 12 },
      ],
      [
        { year: 2022, revenue: 13_500_000, ebitda: 2_300_000 },
        { year: 2023, revenue: 21_400_000, ebitda: 4_900_000 },
        { year: 2024, revenue: 34_000_000, ebitda: 8_800_000 },
      ],
    ),
    company(
      "co_keystone",
      "Keystone Cyber",
      "MDR for industrial control systems",
      "saas",
      "series_b",
      10,
      24_000_000,
      32_000_000,
      280_000_000,
      9,
      82,
      25_000,
      2019,
      11,
      11,
      false,
      "Keystone provides 24/7 managed detection and response purpose-built for industrial control systems in manufacturing, utilities, and critical infrastructure. We protect 740 sites globally.",
      [
        "$24M ARR, 82% growth, 9% EBITDA margin",
        "740 protected sites across 19 countries",
        "Average detection time: 3.2 minutes",
        "Strong regulatory tailwinds (NIS2, EU Cyber Resilience)",
      ],
      [
        { label: "SOC expansion", percent: 38 },
        { label: "Threat research", percent: 22 },
        { label: "Sales", percent: 25 },
        { label: "G&A", percent: 15 },
      ],
      [
        { year: 2022, revenue: 6_400_000, ebitda: -1_200_000 },
        { year: 2023, revenue: 13_200_000, ebitda: 600_000 },
        { year: 2024, revenue: 24_000_000, ebitda: 2_200_000 },
      ],
    ),
    company(
      "co_pavilion",
      "Pavilion Family Brands",
      "Buy-and-build platform for premium home & garden brands",
      "consumer",
      "growth",
      11,
      96_000_000,
      40_000_000,
      390_000_000,
      20,
      24,
      50_000,
      2016,
      0,
      0,
      false,
      "Pavilion is a profitable operator of nine premium home and garden brands acquired and integrated into a shared back-office and e-commerce platform. We continue to roll up small founder-led brands at attractive multiples.",
      [
        "$96M revenue, 20% EBITDA margin",
        "9 brands operated under shared platform",
        "Track record of 3 acquisitions / year at <5x EBITDA",
        "Cross-brand customer base of 870,000",
      ],
      [
        { label: "Acquisition capital", percent: 70 },
        { label: "Platform integration", percent: 15 },
        { label: "Brand marketing", percent: 10 },
        { label: "Working capital", percent: 5 },
      ],
      [
        { year: 2022, revenue: 64_000_000, ebitda: 11_500_000 },
        { year: 2023, revenue: 78_000_000, ebitda: 14_700_000 },
        { year: 2024, revenue: 96_000_000, ebitda: 19_300_000 },
      ],
    ),
  ];

  await db.insert(companiesTable).values(companies);
  console.log(`Inserted ${companies.length} companies`);

  const investors = [
    {
      id: "inv_braxton",
      name: "Braxton Capital Partners",
      type: "private_equity",
      tagline: "Lower middle-market growth equity for profitable founders",
      location: "New York, NY",
      avatarUrl:
        "https://api.dicebear.com/9.x/initials/svg?seed=Braxton%20Capital&backgroundColor=0a4d8f",
      aum: "1_800_000_000".replaceAll("_", ""),
      dealsCompleted: 47,
      checkSizeMin: "5000000",
      checkSizeMax: "75000000",
      focusSectors: ["saas", "fintech", "healthcare", "industrial"],
      stagePreferences: ["series_b", "series_c", "growth"],
      verified: true,
      featured: true,
      bio: "Braxton Capital Partners is a $1.8B growth equity firm investing in profitable, founder-led businesses across software, fintech, healthcare, and industrials. We make minority and majority investments alongside management teams who want a real partner, not a passenger.",
      thesis:
        "We back capital-efficient businesses past product-market fit that are growing 30%+ with positive unit economics. We do not chase momentum; we underwrite to a 5-7 year hold and an internal compounding rate of 25%+.",
      notableInvestments: [
        { companyName: "Atlas Practice Management", year: 2021, outcome: "Sold to Roper" },
        { companyName: "Forge Logistics", year: 2019, outcome: "IPO 2024" },
        { companyName: "Linden Health", year: 2022, outcome: "Active, 4x markup" },
      ],
      partners: [
        { name: "Margaret Holloway", title: "Managing Partner", avatarUrl: "https://api.dicebear.com/9.x/personas/svg?seed=Margaret%20Holloway" },
        { name: "Devon Cross", title: "Partner", avatarUrl: "https://api.dicebear.com/9.x/personas/svg?seed=Devon%20Cross" },
        { name: "Felix Wong", title: "Partner", avatarUrl: "https://api.dicebear.com/9.x/personas/svg?seed=Felix%20Wong" },
      ],
    },
    {
      id: "inv_meridian_growth",
      name: "Meridian Growth Fund III",
      type: "private_equity",
      tagline: "Buy-and-build platforms in fragmented industrial markets",
      location: "London, UK",
      avatarUrl: "https://api.dicebear.com/9.x/initials/svg?seed=Meridian%20Growth&backgroundColor=11567a",
      aum: "2400000000",
      dealsCompleted: 31,
      checkSizeMin: "10000000",
      checkSizeMax: "120000000",
      focusSectors: ["industrial", "energy", "real_estate", "consumer"],
      stagePreferences: ["growth", "pre_ipo"],
      verified: true,
      featured: true,
      bio: "Meridian is a Europe-focused growth fund with $2.4B AUM. We specialize in building category leaders by combining a strong platform with disciplined add-on acquisitions in fragmented industrial and consumer markets.",
      thesis:
        "Pricing power, replacement cost moats, and recurring revenue. We bring an in-house operating team that has executed 80+ integrations.",
      notableInvestments: [
        { companyName: "Halewood Industrial Coatings", year: 2018, outcome: "Sold to KKR 2023" },
        { companyName: "Tessera Renewables", year: 2020, outcome: "IPO 2024 (LSE)" },
        { companyName: "Northshore Modular", year: 2022, outcome: "Active" },
      ],
      partners: [
        { name: "Edward Whitaker", title: "Senior Managing Partner", avatarUrl: "https://api.dicebear.com/9.x/personas/svg?seed=Edward%20Whitaker" },
        { name: "Sofia Lindqvist", title: "Partner, Industrials", avatarUrl: "https://api.dicebear.com/9.x/personas/svg?seed=Sofia%20Lindqvist" },
      ],
    },
    {
      id: "inv_northstar",
      name: "Northstar Ventures",
      type: "venture_capital",
      tagline: "Series A and B investor in vertical software & AI",
      location: "San Francisco, CA",
      avatarUrl: "https://api.dicebear.com/9.x/initials/svg?seed=Northstar%20Ventures&backgroundColor=1d6fb8",
      aum: "750000000",
      dealsCompleted: 89,
      checkSizeMin: "2000000",
      checkSizeMax: "20000000",
      focusSectors: ["saas", "ai", "fintech", "healthcare"],
      stagePreferences: ["series_a", "series_b"],
      verified: true,
      featured: true,
      bio: "Northstar is a $750M early growth fund investing in vertical software and applied AI businesses with capital-efficient unit economics. We typically lead Series A and follow on through Series C.",
      thesis: "Software as a service of record. We index toward founders who treat their P&L as a product surface.",
      notableInvestments: [
        { companyName: "Aperture Health", year: 2020, outcome: "Sold to UnitedHealth 2024" },
        { companyName: "Beacon Logistics", year: 2021, outcome: "Active, 6x markup" },
        { companyName: "Cipher Markets", year: 2022, outcome: "Active" },
      ],
      partners: [
        { name: "Jennifer Hartwell", title: "Founding Partner", avatarUrl: "https://api.dicebear.com/9.x/personas/svg?seed=Jennifer%20Hartwell" },
        { name: "Raj Patel", title: "Partner", avatarUrl: "https://api.dicebear.com/9.x/personas/svg?seed=Raj%20Patel" },
        { name: "Cara Nguyen", title: "Partner", avatarUrl: "https://api.dicebear.com/9.x/personas/svg?seed=Cara%20Nguyen" },
      ],
    },
    {
      id: "inv_juniper",
      name: "Juniper Hedged Strategies",
      type: "hedge_fund",
      tagline: "Long-duration capital for late-stage private growth",
      location: "Boston, MA",
      avatarUrl: "https://api.dicebear.com/9.x/initials/svg?seed=Juniper%20Hedged&backgroundColor=0f3a6e",
      aum: "5200000000",
      dealsCompleted: 22,
      checkSizeMin: "20000000",
      checkSizeMax: "200000000",
      focusSectors: ["fintech", "ai", "healthcare", "consumer"],
      stagePreferences: ["growth", "pre_ipo"],
      verified: true,
      featured: false,
      bio: "Juniper is a $5.2B multi-strategy fund whose private growth book takes long-duration positions in late-stage businesses with line of sight to public markets within 36 months.",
      thesis: "We underwrite to public-market comparables. We are long-duration partners through the IPO window.",
      notableInvestments: [
        { companyName: "Halcyon Payments", year: 2019, outcome: "IPO 2023" },
        { companyName: "Cobalt Cloud", year: 2020, outcome: "Acquired by Snowflake" },
      ],
      partners: [
        { name: "Lawrence Greene", title: "PM, Private Growth", avatarUrl: "https://api.dicebear.com/9.x/personas/svg?seed=Lawrence%20Greene" },
        { name: "Anna Voss", title: "Director, Diligence", avatarUrl: "https://api.dicebear.com/9.x/personas/svg?seed=Anna%20Voss" },
      ],
    },
    {
      id: "inv_atelier",
      name: "Atelier Family Office",
      type: "family_office",
      tagline: "Multi-generational capital from a European industrial family",
      location: "Amsterdam, NL",
      avatarUrl: "https://api.dicebear.com/9.x/initials/svg?seed=Atelier%20Family&backgroundColor=11567a",
      aum: "1100000000",
      dealsCompleted: 38,
      checkSizeMin: "1000000",
      checkSizeMax: "25000000",
      focusSectors: ["consumer", "real_estate", "energy", "industrial"],
      stagePreferences: ["series_b", "series_c", "growth"],
      verified: true,
      featured: true,
      bio: "Atelier is the direct investing arm of a fourth-generation Dutch industrial family. We invest patient, evergreen capital in operating businesses that compound over decades, not quarters.",
      thesis: "We never need to sell. We back operators with long horizons and integrity to match.",
      notableInvestments: [
        { companyName: "Vredes Bakkerij", year: 2014, outcome: "Active, 8x markup" },
        { companyName: "Tellus Forestry", year: 2016, outcome: "Active" },
        { companyName: "Halifax Logistics", year: 2019, outcome: "Active" },
      ],
      partners: [
        { name: "Willem de Boer", title: "Principal", avatarUrl: "https://api.dicebear.com/9.x/personas/svg?seed=Willem%20de%20Boer" },
        { name: "Lieke Smit", title: "Investment Director", avatarUrl: "https://api.dicebear.com/9.x/personas/svg?seed=Lieke%20Smit" },
      ],
    },
    {
      id: "inv_chen",
      name: "Daniel Chen",
      type: "individual",
      tagline: "Operator-investor, ex-COO of two scaled SaaS businesses",
      location: "San Francisco, CA",
      avatarUrl: "https://api.dicebear.com/9.x/personas/svg?seed=Daniel%20Chen",
      aum: "42000000",
      dealsCompleted: 64,
      checkSizeMin: "100000",
      checkSizeMax: "1500000",
      focusSectors: ["saas", "ai", "fintech"],
      stagePreferences: ["seed", "series_a"],
      verified: true,
      featured: true,
      bio: "Daniel is an active angel and operator-investor. He was COO at two SaaS businesses that scaled past $200M ARR and exited via IPO and strategic. He focuses on founders building disciplined, capital-efficient businesses.",
      thesis: "Profitable software is a category. I write checks where the founder treats burn as a tool, not a strategy.",
      notableInvestments: [
        { companyName: "Solstice Networks", year: 2020, outcome: "Sold to Cisco 2024" },
        { companyName: "Crosswalk Pay", year: 2021, outcome: "Active" },
        { companyName: "Meridian Health", year: 2022, outcome: "Active" },
      ],
      partners: [
        { name: "Daniel Chen", title: "Principal", avatarUrl: "https://api.dicebear.com/9.x/personas/svg?seed=Daniel%20Chen" },
      ],
    },
    {
      id: "inv_morales",
      name: "Isabella Morales",
      type: "individual",
      tagline: "Healthcare operator and physician investor",
      location: "Miami, FL",
      avatarUrl: "https://api.dicebear.com/9.x/personas/svg?seed=Isabella%20Morales",
      aum: "18000000",
      dealsCompleted: 31,
      checkSizeMin: "50000",
      checkSizeMax: "750000",
      focusSectors: ["healthcare"],
      stagePreferences: ["seed", "series_a", "series_b"],
      verified: true,
      featured: false,
      bio: "Practicing cardiologist and operator who has served on the board of three healthcare growth companies. Invests primarily in care delivery, devices, and clinical workflow software.",
      thesis: "If you cannot show me a mechanism by which patient outcomes improve, I am not the right investor.",
      notableInvestments: [
        { companyName: "Verda Cardiology", year: 2021, outcome: "Active" },
        { companyName: "OrthoFlow", year: 2022, outcome: "Active" },
      ],
      partners: [
        { name: "Isabella Morales, MD", title: "Principal", avatarUrl: "https://api.dicebear.com/9.x/personas/svg?seed=Isabella%20Morales" },
      ],
    },
    {
      id: "inv_summit",
      name: "Summit Industrial Partners",
      type: "private_equity",
      tagline: "Control buyouts of profitable industrial niche leaders",
      location: "Chicago, IL",
      avatarUrl: "https://api.dicebear.com/9.x/initials/svg?seed=Summit%20Industrial&backgroundColor=0a4d8f",
      aum: "3100000000",
      dealsCompleted: 53,
      checkSizeMin: "25000000",
      checkSizeMax: "300000000",
      focusSectors: ["industrial", "energy", "real_estate"],
      stagePreferences: ["growth", "pre_ipo"],
      verified: true,
      featured: false,
      bio: "Summit Industrial Partners makes control investments in profitable, niche-leader industrial businesses with $20M-$200M of EBITDA across North America and Europe.",
      thesis: "Pricing power, customer concentration discipline, and replacement-cost moats. We hold for 5-8 years and use modest leverage.",
      notableInvestments: [
        { companyName: "Glenmark Coatings", year: 2017, outcome: "Sold to Sherwin-Williams" },
        { companyName: "Apex Materials", year: 2019, outcome: "Active" },
        { companyName: "Harborline Maritime", year: 2022, outcome: "Active" },
      ],
      partners: [
        { name: "Charles Whitfield", title: "Senior Partner", avatarUrl: "https://api.dicebear.com/9.x/personas/svg?seed=Charles%20Whitfield" },
        { name: "Maria Esposito", title: "Partner", avatarUrl: "https://api.dicebear.com/9.x/personas/svg?seed=Maria%20Esposito" },
      ],
    },
    {
      id: "inv_okafor",
      name: "Tunde Okafor",
      type: "individual",
      tagline: "Fintech founder turned investor",
      location: "London, UK",
      avatarUrl: "https://api.dicebear.com/9.x/personas/svg?seed=Tunde%20Okafor",
      aum: "65000000",
      dealsCompleted: 78,
      checkSizeMin: "250000",
      checkSizeMax: "3000000",
      focusSectors: ["fintech", "ai", "consumer"],
      stagePreferences: ["seed", "series_a"],
      verified: true,
      featured: true,
      bio: "Tunde founded a payments business that exited for $1.4B in 2019. Since then he has built a portfolio of 78 fintech and applied AI investments and serves on six boards.",
      thesis: "Underwrite the founder, then the unit economics, then the market — in that order.",
      notableInvestments: [
        { companyName: "Ledgerlane", year: 2020, outcome: "Active, 11x markup" },
        { companyName: "Folio Wealth", year: 2021, outcome: "Active" },
      ],
      partners: [
        { name: "Tunde Okafor", title: "Principal", avatarUrl: "https://api.dicebear.com/9.x/personas/svg?seed=Tunde%20Okafor" },
      ],
    },
    {
      id: "inv_redleaf",
      name: "Redleaf Syndicate",
      type: "syndicate",
      tagline: "Curated SPV access to vetted late-stage rounds",
      location: "Toronto, ON",
      avatarUrl: "https://api.dicebear.com/9.x/initials/svg?seed=Redleaf%20Syndicate&backgroundColor=1d6fb8",
      aum: "240000000",
      dealsCompleted: 41,
      checkSizeMin: "500000",
      checkSizeMax: "10000000",
      focusSectors: ["saas", "ai", "fintech", "healthcare"],
      stagePreferences: ["series_b", "series_c", "growth"],
      verified: true,
      featured: false,
      bio: "Redleaf is a syndicate of 1,200+ accredited investors and small family offices that pools capital into curated SPVs for late-stage private rounds. Average SPV size is $4.2M.",
      thesis: "Selective access. We pass on more than we close.",
      notableInvestments: [
        { companyName: "Plenary Health", year: 2022, outcome: "Active" },
        { companyName: "Scribe AI", year: 2023, outcome: "Active" },
      ],
      partners: [
        { name: "Mira Patel", title: "Lead Organizer", avatarUrl: "https://api.dicebear.com/9.x/personas/svg?seed=Mira%20Patel" },
        { name: "Liam Brock", title: "Diligence Lead", avatarUrl: "https://api.dicebear.com/9.x/personas/svg?seed=Liam%20Brock" },
      ],
    },
    {
      id: "inv_archipelago",
      name: "Archipelago Family Holdings",
      type: "family_office",
      tagline: "Singapore-based multi-family office across APAC and EU",
      location: "Singapore",
      avatarUrl: "https://api.dicebear.com/9.x/initials/svg?seed=Archipelago&backgroundColor=11567a",
      aum: "2700000000",
      dealsCompleted: 29,
      checkSizeMin: "5000000",
      checkSizeMax: "60000000",
      focusSectors: ["consumer", "real_estate", "industrial", "healthcare"],
      stagePreferences: ["growth", "pre_ipo"],
      verified: true,
      featured: false,
      bio: "Archipelago manages capital across four founding families with deep operating roots in Southeast Asia and Continental Europe. We focus on durable cash-flow businesses.",
      thesis: "Quality of management is the only durable edge. We invest behind teams we want to spend a decade with.",
      notableInvestments: [
        { companyName: "Nusantara Hospitality", year: 2018, outcome: "Active" },
        { companyName: "Coral Maritime", year: 2020, outcome: "Active" },
      ],
      partners: [
        { name: "Wei-Lin Tan", title: "Head of Direct Investments", avatarUrl: "https://api.dicebear.com/9.x/personas/svg?seed=Wei-Lin%20Tan" },
      ],
    },
    {
      id: "inv_kessler",
      name: "Kessler Krieger",
      type: "individual",
      tagline: "Industrials operator, 3 platform exits",
      location: "Berlin, Germany",
      avatarUrl: "https://api.dicebear.com/9.x/personas/svg?seed=Kessler%20Krieger",
      aum: "92000000",
      dealsCompleted: 19,
      checkSizeMin: "1000000",
      checkSizeMax: "10000000",
      focusSectors: ["industrial", "energy"],
      stagePreferences: ["series_b", "growth"],
      verified: true,
      featured: false,
      bio: "Three-time CEO who has built and sold platforms in coatings, machinery, and renewables. Now investing personal capital in profitable industrial businesses across the DACH region.",
      thesis: "Cash conversion is destiny. I focus on businesses where every euro of EBITDA becomes a euro of free cash flow.",
      notableInvestments: [
        { companyName: "Schwarzwald Maschinenbau", year: 2020, outcome: "Active" },
      ],
      partners: [
        { name: "Kessler Krieger", title: "Principal", avatarUrl: "https://api.dicebear.com/9.x/personas/svg?seed=Kessler%20Krieger" },
      ],
    },
  ];

  await db.insert(investorsTable).values(investors);
  console.log(`Inserted ${investors.length} investors`);

  const dealStatuses = ["open", "closing_soon", "funded", "closed"] as const;
  const deals = companies.flatMap((c, idx) => {
    const status = dealStatuses[idx % dealStatuses.length];
    return [
      {
        id: `deal_${c.id}`,
        companyId: c.id,
        companyName: c.name,
        industry: c.industry,
        raiseAmount: c.raiseAmount,
        committedAmount: c.committedAmount,
        status,
        openedAt: new Date(Date.now() - (idx * 7 + 3) * 86400000),
        closesAt: new Date(Date.now() + (45 - idx * 2) * 86400000),
      },
    ];
  });

  // additional historic closed deals
  for (let i = 0; i < 8; i++) {
    deals.push({
      id: `deal_hist_${i}`,
      companyId: companies[i % companies.length].id,
      companyName: companies[i % companies.length].name,
      industry: companies[i % companies.length].industry,
      raiseAmount: String(8_000_000 + i * 4_500_000),
      committedAmount: String(8_000_000 + i * 4_500_000),
      status: i % 2 === 0 ? "funded" : "closed",
      openedAt: new Date(Date.now() - (180 + i * 23) * 86400000),
      closesAt: new Date(Date.now() - (90 + i * 18) * 86400000),
    });
  }

  await db.insert(dealsTable).values(deals);
  console.log(`Inserted ${deals.length} deals`);

  const activityKinds = [
    {
      kind: "deal_funded",
      title: "Clearwave Health closed Series C",
      subtitle: "$45M committed across 38 investors",
      amount: "45000000",
      companyId: "co_clearwave",
    },
    {
      kind: "investor_joined",
      title: "Atelier Family Office joined CapitalBridge",
      subtitle: "Multi-generational capital from a European industrial family",
      amount: null,
      investorId: "inv_atelier",
    },
    {
      kind: "deal_opened",
      title: "Orbit Logistics opened Series B",
      subtitle: "$18M raise targeting routing platform expansion",
      amount: "18000000",
      companyId: "co_orbit",
    },
    {
      kind: "milestone",
      title: "Meridian Capital Markets hit $9.2B in routed assets",
      subtitle: "47 enterprise customers and 11 jurisdictions",
      amount: null,
      companyId: "co_meridian",
    },
    {
      kind: "listing_created",
      title: "Northwind Renewables listed for capital",
      subtitle: "412 MW operating, 1.1 GW pipeline",
      amount: "75000000",
      companyId: "co_northwind",
    },
    {
      kind: "deal_funded",
      title: "Lumen vertical SaaS Series A oversubscribed",
      subtitle: "Raise upsized from $12M to $14M",
      amount: "14000000",
      companyId: "co_lumen",
    },
    {
      kind: "investor_joined",
      title: "Tunde Okafor joined as a verified angel",
      subtitle: "78 fintech and AI investments to date",
      amount: null,
      investorId: "inv_okafor",
    },
    {
      kind: "deal_opened",
      title: "Relay Intelligence opened Series B",
      subtitle: "$26M raise, applied AI for insurance claims",
      amount: "26000000",
      companyId: "co_relay",
    },
    {
      kind: "milestone",
      title: "Atrium Modular delivered 4,300th unit",
      subtitle: "Backlog now $312M contracted",
      amount: null,
      companyId: "co_atrium",
    },
    {
      kind: "deal_funded",
      title: "Silvermark Skincare Series B closed",
      subtitle: "Practitioner channel expansion fully funded",
      amount: "20000000",
      companyId: "co_silvermark",
    },
    {
      kind: "investor_joined",
      title: "Summit Industrial Partners joined CapitalBridge",
      subtitle: "Control buyouts of profitable industrial niche leaders",
      amount: null,
      investorId: "inv_summit",
    },
    {
      kind: "deal_opened",
      title: "Pavilion Family Brands opened growth round",
      subtitle: "Capital for buy-and-build in home & garden",
      amount: "40000000",
      companyId: "co_pavilion",
    },
  ];

  const activityRows = activityKinds.map((a, i) => ({
    id: `act_${i}`,
    kind: a.kind,
    title: a.title,
    subtitle: a.subtitle,
    amount: a.amount,
    timestamp: new Date(Date.now() - i * 4 * 3600 * 1000),
    companyId: a.companyId ?? null,
    investorId: a.investorId ?? null,
  }));

  await db.insert(activityTable).values(activityRows);
  console.log(`Inserted ${activityRows.length} activity events`);

  console.log("Seed complete.");
  process.exit(0);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
